project:
  type: website
  output-dir: docs

website:
  title: "Progetto Basso Canavese {{< fa volleyball size=normalsize >}}"
  navbar:
    right:
      - icon: youtube
        href: https://youtube.com/playlist?list=PLuLJwY97FamcsQrlt0uSira4yKeef-vSt
format:
  html:
    theme: yeti
    css: styles.css

editor: source