project:
  type: website
  output-dir: docs

website:
  title: "Basso Canavese Volley Foglizzo"
  favicon: data/004_images/foxvolleyball3.png
  navbar:
    logo: "foxvolleyball3.png"
    right:
      - icon: youtube
        href: https://youtube.com/playlist?list=PLuLJwY97FamcsQrlt0uSira4yKeef-vSt
      - text: Calendari
        menu: 
          - text: "Prima fase"
            href: https://fipavonline.it/main/gare_girone/40670/1
          - text: "Seconda fase"
            href: https://fipavonline.it/main/gare_girone/42353
      - text: Classifica
        menu: 
          - text: "Prima fase"
            href: https://fipavonline.it/main/classifica/40670
          - text: "Seconda fase"
            href: https://fipavonline.it/main/classifica/42353
format:
  html:
    theme: yeti
    css: styles.css

editor: source