---
title: "Foglio gara"
subtitle: "PGS Foglizzese - Parella"
editor: visual
format:
  html:
    toc: false
    theme: journal
    page-layout: custom
    number-sections: false
    css: style.css
execute:
  echo: false
  message: false
  warning: false
---

```{r}
#| include: false
library(tidyverse)
library(datavolley)
library(gt)
library(gtExtras)
library(patchwork)
source(paste0(here::here(), "/scripts/999_utils.R"))
# Read data
file <- fs::dir_ls(paste0(here::here(), "/data/002_Partite/2022-10-15_VolleyParella"), 
                   regexp = "dvw$")
x <- dv_read(file)
noi <- teams(x)[1]
loro <- teams(x)[teams(x) != noi]
px <- plays(x)
```


# Giocatrici pericolose

```{r}
tibble(Numero = c(88),
       Nome = c("Peppa pig"),
       Attacco = c("- Attacca molto forte, ma sempre in *diagonale*",
                   glue::glue("- All'andata ha fatto {px %>% filter(player_number == 6, skill == 'Attack') %>% summarise(n = n()) %>% pull(n)} attacchi"), ""),
       Battuta = c("- Attacca molto forte, ma sempre in *diagonale*",
                   glue::glue("- All'andata ha fatto {px %>% filter(player_number == 6, skill == 'Attack') %>% summarise(n = n()) %>% pull(n)} attacchi"),
                              "- hdflksdjfk ")) %>% 
    group_by(Numero, Nome) %>% 
    gt()




```







# Attacchi

```{r}
#| fig-width: 2
attack_rate <- px %>%
    dplyr::filter(skill == "Attack",
                  team != "PGS Foglizzese") %>%
    filter(grepl("2|3|4", start_zone)) %>% 
    group_by(team, start_zone, end_zone) %>%
    dplyr::summarize(n_attacks = n()) %>%
    mutate(rate = n_attacks/sum(n_attacks)) %>%
    ungroup %>% 
    bind_cols(dv_xy(.$start_zone, end = "upper")) %>% 
    rename(start_x = x, start_y = y) %>% 
    bind_cols(dv_xy(.$end_zone, end = "lower")) %>% 
    rename(end_x = x, end_y = y)

# Posto 2
p1 <- attack_rate %>%
    filter(start_zone == 2) %>% 
    ggplot(aes(end_x, end_y)) +
    geom_tile(aes(fill = rate), show.legend = FALSE) +
    geom_text(aes(label = n_attacks)) +
    scale_fill_gradient2(low = "white",
                         high = "red",
                         name = "Scala Intensità") +
    ggcourt(labels = c("", ""), court = "lower") +
    ggforce::geom_circle(aes(x0=1, y0=3.5, r=.1),
                fill='red', lwd=1, inherit.aes=FALSE) +
    labs(title = "Attacco da P2") +
    theme(plot.title = element_text(hjust = .5),
          plot.margin = unit(c(0, 0, 0, 0), "cm"))

# Posto 3
p2 <- attack_rate %>%
    filter(start_zone == 3) %>% 
    ggplot(aes(end_x, end_y)) +
    geom_tile(aes(fill = rate), show.legend = FALSE) +
    geom_text(aes(label = n_attacks)) +
    scale_fill_gradient2(low = "white",
                         high = "red",
                         name = "Scala Intensità") +
    ggcourt(labels = c("", ""), court = "lower") +
    ggforce::geom_circle(aes(x0=2, y0=3.5, r=.1),
                         fill='red', lwd=1, inherit.aes=FALSE) +
    labs(title = "Attacco da P3") +
    theme(plot.title = element_text(hjust = .5),,
          plot.margin = unit(c(0, 0, 0, 0), "cm"))

# Posto 4
p3 <- attack_rate %>%
    filter(start_zone == 4) %>% 
    ggplot(aes(end_x, end_y)) +
    geom_tile(aes(fill = rate), show.legend = FALSE) +
    geom_text(aes(label = n_attacks)) +
    scale_fill_gradient2(low = "white",
                         high = "red",
                         name = "Scala Intensità") +
    ggcourt(labels = c("", ""), court = "lower") +
    ggforce::geom_circle(aes(x0=3, y0=3.5, r=.1),
                         fill='red', lwd=1, inherit.aes=FALSE) +
    labs(title = "Attacco da P4") +
    theme(plot.title = element_text(hjust = .5),
          plot.margin = unit(c(0, 0, 0, 0), "cm"))

pall <- p1 + p2 + p3
ggsave(pall, file = "test.jpeg", dpi = 300, scale = 1.5)
tmp <- magick::image_read("test.jpeg")
fs::file_delete("test.jpeg")
pall <- magick::image_trim(tmp)


```

fgs;dlkhfs
fsd f's


# fjs;ldjf